name: CI

on: [push]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - uses: php-actions/composer@v1

      - name: Persist working directory
        uses: actions/upload-artifact@v1
        with:
          name: pwd
          path: ./

  test:
    runs-on: ubuntu-latest
    needs: build

    steps:
      - name: Download persisted dependencies
        uses: actions/download-artifact@v1
        with:
          name: pwd
          path: ./

      - uses: php-actions/phpunit@v1